import = [
    "~/.config/alacritty/catppuccin-macchiato.toml",
    # "~/.config/alacritty/dracula.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font.bold]
family = "Jetbrainsmono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Jetbrainsmono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Jetbrainsmono Nerd Font Mono"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>_ "

[window]
# decoration = "none"
dynamic_padding = true
opacity = 0.85

[window.padding]
x = 0
y = 0
