import = [
    "~/.config/alacritty/catppuccin-macchiato.toml",
    # "~/.config/alacritty/dracula.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size=12.0

[font.bold]
family = "GoMono Nerd Font"
style = "Bold"

[font.italic]
family = "GoMono Nerd Font"
style = "Italic"

[font.normal]
family = "GoMono Nerd Font"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[window]
# decoration = "none"
dynamic_padding = true
opacity = 0.85

[window.padding]
x = 0
y = 0
